--EMG schema extension to support biome search (represents an implementation of the preorder tree traversal model)

--Author: Maxim Scheremetjew, EMBL-EBI, InterPro

--Table Drop statements
DROP TABLE biome_hierarchy_tree cascade constraints;
DROP TABLE biome_study cascade constraints;

--Alter table statements
ALTER TABLE sample DROP COLUMN biome_id;

--Sequence drop statements
DROP SEQUENCE "EMG"."BIOME_STUDY_SEQ";

--DDL statements for tables biome_hierarchy_tree and biome_study
--Login as emg schema owner and run the following statements

-- biome_hierarchy_tree table
CREATE TABLE biome_hierarchy_tree (
         biome_id   NUMBER(4)     PRIMARY KEY,
         biome_name VARCHAR2(60)  NOT NULL,
         lft        NUMBER(4)     NOT NULL,
         rgt        NUMBER(4)     NOT NULL,
         depth      NUMBER(1)     NOT NULL,
         lineage    VARCHAR2(110)  NOT NULL
         );

GRANT SELECT ON biome_hierarchy_tree TO "EMGAPP";
GRANT SELECT ON biome_hierarchy_tree TO "EMG_USER";
GRANT ALTER ON biome_hierarchy_tree TO "EMG_USER";
GRANT SELECT ON biome_hierarchy_tree TO "EMG_READ";
GRANT DELETE ON biome_hierarchy_tree TO "EMG_USER";

--alter sample table
ALTER TABLE sample ADD biome_id NUMBER(4) CONSTRAINT biome_id_fk2 REFERENCES biome_hierarchy_tree (biome_id);


-- biome_study table
CREATE TABLE biome_study (
         study_id NUMBER(10)    PRIMARY KEY,
         accession      VARCHAR2(40)  NOT NULL,
         biome_id NUMBER(4)     NOT NULL
                                CONSTRAINT biome_id_fk REFERENCES biome_hierarchy_tree (biome_id)
         );

GRANT SELECT ON biome_study TO "EMGAPP";
GRANT SELECT ON biome_study TO "EMG_USER";
GRANT ALTER ON biome_study TO "EMG_USER";
GRANT SELECT ON biome_study TO "EMG_READ";
GRANT DELETE ON biome_study TO "EMG_USER";

CREATE SEQUENCE  BIOME_STUDY_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE;

GRANT SELECT ON BIOME_STUDY_SEQ TO "EMGAPP";
GRANT SELECT ON BIOME_STUDY_SEQ TO "EMG_USER";
GRANT ALTER ON BIOME_STUDY_SEQ TO "EMG_USER";
GRANT SELECT ON BIOME_STUDY_SEQ TO "EMG_READ";

create or replace
trigger "EMG"."BIOME_STUDY_TRIGGER"
BEFORE INSERT ON BIOME_STUDY
FOR EACH ROW
BEGIN
if :new.STUDY_ID is null then
  select BIOME_STUDY_SEQ.nextval into :new.STUDY_ID
  from dual;
END IF;
END;
/

INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (0,1,964,1,'root','root');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (1,2,155,2,'Engineered','root:Engineered');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (2,3,14,3,'Bioreactor','root:Engineered:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (3,4,13,4,'Continuous culture','root:Engineered:Bioreactor:Continuous culture');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (4,5,8,5,'Marine intertidal flat sediment inoculum','root:Engineered:Bioreactor:Continuous culture:Marine intertidal flat sediment inoculum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (5,6,7,6,'Wadden Sea-Germany','root:Engineered:Bioreactor:Continuous culture:Marine intertidal flat sediment inoculum:Wadden Sea-Germany');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (6,9,12,5,'Marine sediment inoculum','root:Engineered:Bioreactor:Continuous culture:Marine sediment inoculum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (7,10,11,6,'Wadden Sea-Germany','root:Engineered:Bioreactor:Continuous culture:Marine sediment inoculum:Wadden Sea-Germany');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (8,15,46,3,'Bioremediation','root:Engineered:Bioremediation');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (9,16,21,4,'Hydrocarbon','root:Engineered:Bioremediation:Hydrocarbon');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (10,17,20,5,'Benzene','root:Engineered:Bioremediation:Hydrocarbon:Benzene');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (11,18,19,6,'Bioreactor','root:Engineered:Bioremediation:Hydrocarbon:Benzene:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (12,22,23,4,'Metal','root:Engineered:Bioremediation:Metal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (13,24,27,4,'Persistent organic pollutants (POP)','root:Engineered:Bioremediation:Persistent organic pollutants (POP)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (14,25,26,5,'Polycyclic aromatic hydrocarbons','root:Engineered:Bioremediation:Persistent organic pollutants (POP):Polycyclic aromatic hydrocarbons');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (15,28,35,4,'Terephthalate','root:Engineered:Bioremediation:Terephthalate');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (16,29,34,5,'Wastewater','root:Engineered:Bioremediation:Terephthalate:Wastewater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (17,30,31,6,'Activated sludge','root:Engineered:Bioremediation:Terephthalate:Wastewater:Activated sludge');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (18,32,33,6,'Bioreactor','root:Engineered:Bioremediation:Terephthalate:Wastewater:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (19,36,45,4,'Tetrachloroethylene and derivatives','root:Engineered:Bioremediation:Tetrachloroethylene and derivatives');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (20,37,40,5,'Chloroethene','root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Chloroethene');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (21,38,39,6,'Bioreactor','root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Chloroethene:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (22,41,44,5,'Tetrachloroethylene','root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Tetrachloroethylene');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (23,42,43,6,'Bioreactor','root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Tetrachloroethylene:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (24,47,54,3,'Biotransformation','root:Engineered:Biotransformation');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (25,48,49,4,'Microbial enhanced oil recovery','root:Engineered:Biotransformation:Microbial enhanced oil recovery');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (26,50,51,4,'Microbial solubilization of coal','root:Engineered:Biotransformation:Microbial solubilization of coal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (27,52,53,4,'Mixed alcohol bioreactor','root:Engineered:Biotransformation:Mixed alcohol bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (28,55,56,3,'Built environment','root:Engineered:Built environment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (29,57,68,3,'Food production','root:Engineered:Food production');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (30,58,59,4,'Dairy products','root:Engineered:Food production:Dairy products');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (31,60,61,4,'Fermented beverages','root:Engineered:Food production:Fermented beverages');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (32,62,63,4,'Fermented seafood','root:Engineered:Food production:Fermented seafood');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (33,64,65,4,'Fermented vegetables','root:Engineered:Food production:Fermented vegetables');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (34,66,67,4,'Silage fermentation','root:Engineered:Food production:Silage fermentation');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (35,69,72,3,'Industrial production','root:Engineered:Industrial production');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (36,70,71,4,'Engineered product','root:Engineered:Industrial production:Engineered product');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (37,73,86,3,'Lab enrichment','root:Engineered:Lab enrichment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (38,74,83,4,'Defined media','root:Engineered:Lab enrichment:Defined media');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (39,75,76,5,'Aerobic media','root:Engineered:Lab enrichment:Defined media:Aerobic media');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (40,77,78,5,'Anaerobic media','root:Engineered:Lab enrichment:Defined media:Anaerobic media');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (41,79,82,5,'Marine media','root:Engineered:Lab enrichment:Defined media:Marine media');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (42,80,81,6,'Algoconsortia','root:Engineered:Lab enrichment:Defined media:Marine media:Algoconsortia');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (43,84,85,4,'Undefined media','root:Engineered:Lab enrichment:Undefined media');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (44,87,90,3,'Lab Synthesis','root:Engineered:Lab Synthesis');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (45,88,89,4,'Genetic cross','root:Engineered:Lab Synthesis:Genetic cross');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (46,91,92,3,'Lab synthesis','root:Engineered:Lab synthesis');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (47,93,102,3,'Modeled','root:Engineered:Modeled');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (48,94,95,4,'Simulated communities (DNA mixture)','root:Engineered:Modeled:Simulated communities (DNA mixture)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (49,96,97,4,'Simulated communities (microbial mixture)','root:Engineered:Modeled:Simulated communities (microbial mixture)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (50,98,101,4,'Simulated communities (sequence read mixture)','root:Engineered:Modeled:Simulated communities (sequence read mixture)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (51,99,100,5,'Sanger','root:Engineered:Modeled:Simulated communities (sequence read mixture):Sanger');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (52,103,118,3,'Solid waste','root:Engineered:Solid waste');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (53,104,113,4,'Composting','root:Engineered:Solid waste:Composting');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (54,105,108,5,'Grass','root:Engineered:Solid waste:Composting:Grass');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (55,106,107,6,'Bioreactor','root:Engineered:Solid waste:Composting:Grass:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (56,109,112,5,'Wood','root:Engineered:Solid waste:Composting:Wood');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (57,110,111,6,'Bioreactor','root:Engineered:Solid waste:Composting:Wood:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (58,114,115,4,'Landfill','root:Engineered:Solid waste:Landfill');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (59,116,117,4,'Solid animal waste','root:Engineered:Solid waste:Solid animal waste');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (60,119,154,3,'Wastewater','root:Engineered:Wastewater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (61,120,121,4,'Activated Sludge','root:Engineered:Wastewater:Activated Sludge');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (62,122,133,4,'Industrial wastewater','root:Engineered:Wastewater:Industrial wastewater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (63,123,124,5,'Agricultural wastewater','root:Engineered:Wastewater:Industrial wastewater:Agricultural wastewater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (64,125,126,5,'Landfill leachate','root:Engineered:Wastewater:Industrial wastewater:Landfill leachate');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (65,127,128,5,'Mine water','root:Engineered:Wastewater:Industrial wastewater:Mine water');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (66,129,130,5,'Petrochemical','root:Engineered:Wastewater:Industrial wastewater:Petrochemical');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (67,131,132,5,'Pulp and paper wastewater','root:Engineered:Wastewater:Industrial wastewater:Pulp and paper wastewater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (68,134,153,4,'Nutrient removal','root:Engineered:Wastewater:Nutrient removal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (69,135,140,5,'Biological phosphorus removal','root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (70,136,137,6,'Activated sludge','root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal:Activated sludge');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (71,138,139,6,'Bioreactor','root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal:Bioreactor');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (72,141,144,5,'Dissolved organics (aerobic)','root:Engineered:Wastewater:Nutrient removal:Dissolved organics (aerobic)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (73,142,143,6,'Activated sludge','root:Engineered:Wastewater:Nutrient removal:Dissolved organics (aerobic):Activated sludge');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (74,145,148,5,'Dissolved organics (anaerobic)','root:Engineered:Wastewater:Nutrient removal:Dissolved organics (anaerobic)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (75,146,147,6,'Activated sludge','root:Engineered:Wastewater:Nutrient removal:Dissolved organics (anaerobic):Activated sludge');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (76,149,152,5,'Nitrogen removal','root:Engineered:Wastewater:Nutrient removal:Nitrogen removal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (77,150,151,6,'Anammox','root:Engineered:Wastewater:Nutrient removal:Nitrogen removal:Anammox');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (78,156,521,2,'Environmental','root:Environmental');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (79,157,162,3,'Air','root:Environmental:Air');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (80,158,159,4,'Indoor Air','root:Environmental:Air:Indoor Air');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (81,160,161,4,'Outdoor Air','root:Environmental:Air:Outdoor Air');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (82,163,438,3,'Aquatic','root:Environmental:Aquatic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (83,164,165,4,'Aquaculture','root:Environmental:Aquatic:Aquaculture');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (84,166,249,4,'Freshwater','root:Environmental:Aquatic:Freshwater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (85,167,172,5,'Drinking water','root:Environmental:Aquatic:Freshwater:Drinking water');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (86,168,169,6,'Chlorinated','root:Environmental:Aquatic:Freshwater:Drinking water:Chlorinated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (87,170,171,6,'Delivery networks','root:Environmental:Aquatic:Freshwater:Drinking water:Delivery networks');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (88,173,186,5,'Groundwater','root:Environmental:Aquatic:Freshwater:Groundwater');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (89,174,175,6,'Acid Mine Drainage','root:Environmental:Aquatic:Freshwater:Groundwater:Acid Mine Drainage');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (90,176,177,6,'Cave water','root:Environmental:Aquatic:Freshwater:Groundwater:Cave water');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (91,178,179,6,'Coalbed water','root:Environmental:Aquatic:Freshwater:Groundwater:Coalbed water');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (92,180,181,6,'Contaminated','root:Environmental:Aquatic:Freshwater:Groundwater:Contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (93,182,183,6,'Mine','root:Environmental:Aquatic:Freshwater:Groundwater:Mine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (94,184,185,6,'Mine drainage','root:Environmental:Aquatic:Freshwater:Groundwater:Mine drainage');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (95,187,194,5,'Ice','root:Environmental:Aquatic:Freshwater:Ice');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (96,188,189,6,'Glacial lake','root:Environmental:Aquatic:Freshwater:Ice:Glacial lake');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (97,190,191,6,'Glacier','root:Environmental:Aquatic:Freshwater:Ice:Glacier');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (98,192,193,6,'Ice accretions','root:Environmental:Aquatic:Freshwater:Ice:Ice accretions');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (99,195,196,5,'Lake','root:Environmental:Aquatic:Freshwater:Lake');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (100,197,208,5,'Lentic','root:Environmental:Aquatic:Freshwater:Lentic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (101,198,199,6,'Epilimnion','root:Environmental:Aquatic:Freshwater:Lentic:Epilimnion');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (102,200,201,6,'Hypolimnion','root:Environmental:Aquatic:Freshwater:Lentic:Hypolimnion');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (103,202,203,6,'Limnetic zone','root:Environmental:Aquatic:Freshwater:Lentic:Limnetic zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (104,204,205,6,'Littoral zone','root:Environmental:Aquatic:Freshwater:Lentic:Littoral zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (105,206,207,6,'Sediment','root:Environmental:Aquatic:Freshwater:Lentic:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (106,209,214,5,'Lotic','root:Environmental:Aquatic:Freshwater:Lotic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (107,210,211,6,'Low land river systems','root:Environmental:Aquatic:Freshwater:Lotic:Low land river systems');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (108,212,213,6,'Sediment','root:Environmental:Aquatic:Freshwater:Lotic:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (109,215,222,5,'Lotic ','root:Environmental:Aquatic:Freshwater:Lotic ');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (110,216,217,6,'Low land river systems','root:Environmental:Aquatic:Freshwater:Lotic :Low land river systems');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (111,218,219,6,'Mid stream','root:Environmental:Aquatic:Freshwater:Lotic :Mid stream');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (112,220,221,6,'Sediment','root:Environmental:Aquatic:Freshwater:Lotic :Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (113,223,224,5,'Microbialites','root:Environmental:Aquatic:Freshwater:Microbialites');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (114,225,228,5,'Pond','root:Environmental:Aquatic:Freshwater:Pond');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (115,226,227,6,'Sediment','root:Environmental:Aquatic:Freshwater:Pond:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (116,229,230,5,'Ponds','root:Environmental:Aquatic:Freshwater:Ponds');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (117,231,232,5,'Sediment','root:Environmental:Aquatic:Freshwater:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (118,233,236,5,'Storm water','root:Environmental:Aquatic:Freshwater:Storm water');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (119,234,235,6,'Drainage pipe biofilm','root:Environmental:Aquatic:Freshwater:Storm water:Drainage pipe biofilm');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (120,237,238,5,'Subglacial lake','root:Environmental:Aquatic:Freshwater:Subglacial lake');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (121,239,248,5,'Wetlands','root:Environmental:Aquatic:Freshwater:Wetlands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (122,240,241,6,'Bog','root:Environmental:Aquatic:Freshwater:Wetlands:Bog');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (123,242,243,6,'Marsh','root:Environmental:Aquatic:Freshwater:Wetlands:Marsh');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (124,244,245,6,'Sediment','root:Environmental:Aquatic:Freshwater:Wetlands:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (125,246,247,6,'Swamp','root:Environmental:Aquatic:Freshwater:Wetlands:Swamp');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (126,250,365,4,'Marine','root:Environmental:Aquatic:Marine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (127,251,254,5,'Coastal','root:Environmental:Aquatic:Marine:Coastal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (128,252,253,6,'Sediment','root:Environmental:Aquatic:Marine:Coastal:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (129,255,258,5,'Cold seeps','root:Environmental:Aquatic:Marine:Cold seeps');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (130,256,257,6,'Sediment','root:Environmental:Aquatic:Marine:Cold seeps:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (131,259,262,5,'Fossil','root:Environmental:Aquatic:Marine:Fossil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (132,260,261,6,'Whale fall','root:Environmental:Aquatic:Marine:Fossil:Whale fall');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (133,263,272,5,'Hydrothermal vents','root:Environmental:Aquatic:Marine:Hydrothermal vents');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (134,264,265,6,'Black smokers','root:Environmental:Aquatic:Marine:Hydrothermal vents:Black smokers');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (135,266,267,6,'Diffuse flow','root:Environmental:Aquatic:Marine:Hydrothermal vents:Diffuse flow');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (136,268,269,6,'Microbial mats','root:Environmental:Aquatic:Marine:Hydrothermal vents:Microbial mats');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (137,270,271,6,'Sediment','root:Environmental:Aquatic:Marine:Hydrothermal vents:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (138,273,290,5,'Intertidal zone','root:Environmental:Aquatic:Marine:Intertidal zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (139,274,275,6,'Beach','root:Environmental:Aquatic:Marine:Intertidal zone:Beach');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (140,276,277,6,'Coral reef','root:Environmental:Aquatic:Marine:Intertidal zone:Coral reef');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (141,278,279,6,'Estuary','root:Environmental:Aquatic:Marine:Intertidal zone:Estuary');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (144,280,281,6,'Mangrove swamp','root:Environmental:Aquatic:Marine:Intertidal zone:Mangrove swamp');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (145,282,283,6,'Microbialites','root:Environmental:Aquatic:Marine:Intertidal zone:Microbialites');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (146,284,285,6,'Oil-contaminated','root:Environmental:Aquatic:Marine:Intertidal zone:Oil-contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (147,286,287,6,'Salt marsh','root:Environmental:Aquatic:Marine:Intertidal zone:Salt marsh');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (148,288,289,6,'Sediment','root:Environmental:Aquatic:Marine:Intertidal zone:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (142,291,294,5,'Intertidal Zone','root:Environmental:Aquatic:Marine:Intertidal Zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (143,292,293,6,'Estuary','root:Environmental:Aquatic:Marine:Intertidal Zone:Estuary');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (149,295,306,5,'Intertidal zone ','root:Environmental:Aquatic:Marine:Intertidal zone ');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (150,296,297,6,'Beach','root:Environmental:Aquatic:Marine:Intertidal zone :Beach');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (151,298,299,6,'Coral reef','root:Environmental:Aquatic:Marine:Intertidal zone :Coral reef');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (152,300,301,6,'Estuary','root:Environmental:Aquatic:Marine:Intertidal zone :Estuary');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (153,302,303,6,'Salt marsh','root:Environmental:Aquatic:Marine:Intertidal zone :Salt marsh');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (154,304,305,6,'Sediment','root:Environmental:Aquatic:Marine:Intertidal zone :Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (155,307,308,5,'Marginal Sea','root:Environmental:Aquatic:Marine:Marginal Sea');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (156,309,314,5,'Neritic zone','root:Environmental:Aquatic:Marine:Neritic zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (157,310,311,6,'Oil-contaminated sediment','root:Environmental:Aquatic:Marine:Neritic zone:Oil-contaminated sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (158,312,313,6,'Sediment','root:Environmental:Aquatic:Marine:Neritic zone:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (159,315,316,5,'Neritic Zone','root:Environmental:Aquatic:Marine:Neritic Zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (160,317,322,5,'Neritic zone ','root:Environmental:Aquatic:Marine:Neritic zone ');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (161,318,319,6,'Oil-contaminated sediment','root:Environmental:Aquatic:Marine:Neritic zone :Oil-contaminated sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (162,320,321,6,'Sediment','root:Environmental:Aquatic:Marine:Neritic zone :Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (163,323,338,5,'Oceanic','root:Environmental:Aquatic:Marine:Oceanic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (164,324,325,6,'Abyssal plane','root:Environmental:Aquatic:Marine:Oceanic:Abyssal plane');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (165,326,327,6,'Aphotic zone','root:Environmental:Aquatic:Marine:Oceanic:Aphotic zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (166,328,329,6,'Oil-contaminated','root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (167,330,331,6,'Oil-contaminated sediment','root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (168,332,333,6,'Oil-contaminated sediments','root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated sediments');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (169,334,335,6,'Photic zone','root:Environmental:Aquatic:Marine:Oceanic:Photic zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (170,336,337,6,'Sediment','root:Environmental:Aquatic:Marine:Oceanic:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (171,339,354,5,'Oceanic ','root:Environmental:Aquatic:Marine:Oceanic ');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (172,340,341,6,'Abyssal plane','root:Environmental:Aquatic:Marine:Oceanic :Abyssal plane');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (173,342,343,6,'Aphotic zone','root:Environmental:Aquatic:Marine:Oceanic :Aphotic zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (174,344,345,6,'Benthic','root:Environmental:Aquatic:Marine:Oceanic :Benthic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (175,346,347,6,'Oil-contaminated','root:Environmental:Aquatic:Marine:Oceanic :Oil-contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (176,348,349,6,'Oil-contaminated sediment','root:Environmental:Aquatic:Marine:Oceanic :Oil-contaminated sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (177,350,351,6,'Photic zone','root:Environmental:Aquatic:Marine:Oceanic :Photic zone');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (178,352,353,6,'Sediment','root:Environmental:Aquatic:Marine:Oceanic :Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (179,355,356,5,'Oil seeps','root:Environmental:Aquatic:Marine:Oil seeps');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (180,357,358,5,'Pelagic','root:Environmental:Aquatic:Marine:Pelagic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (181,359,360,5,'Volcanic','root:Environmental:Aquatic:Marine:Volcanic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (182,361,364,5,'Wetlands','root:Environmental:Aquatic:Marine:Wetlands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (183,362,363,6,'Sediment','root:Environmental:Aquatic:Marine:Wetlands:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (184,366,403,4,'Non-marine Saline and Alkaline','root:Environmental:Aquatic:Non-marine Saline and Alkaline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (185,367,374,5,'Alkaline','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (186,368,369,6,'Carbonate','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Carbonate');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (187,370,371,6,'Microbial mats','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Microbial mats');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (188,372,373,6,'Sediment','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (189,375,380,5,'Hypersaline','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (190,376,377,6,'Microbial mats','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline:Microbial mats');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (191,378,379,6,'Sediment','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (192,381,384,5,'Near-boiling (>90C)','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Near-boiling (>90C)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (193,382,383,6,'Alkaline','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Near-boiling (>90C):Alkaline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (194,385,398,5,'Saline','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (195,386,387,6,'Athalassic','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Athalassic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (196,388,389,6,'Epilimnion','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Epilimnion');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (197,390,391,6,'Hypolimnion','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Hypolimnion');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (198,392,393,6,'Microbial mats','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Microbial mats');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (199,394,395,6,'Sediment','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (200,396,397,6,'Thalassic','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Thalassic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (201,399,402,5,'Salt crystallizer ponds','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Salt crystallizer ponds');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (202,400,401,6,'Microbial mats','root:Environmental:Aquatic:Non-marine Saline and Alkaline:Salt crystallizer ponds:Microbial mats');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (203,404,405,4,'Sediment','root:Environmental:Aquatic:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (204,406,433,4,'Thermal springs','root:Environmental:Aquatic:Thermal springs');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (205,407,416,5,'Hot (42-90C)','root:Environmental:Aquatic:Thermal springs:Hot (42-90C)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (206,408,409,6,'Acidic','root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Acidic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (207,410,411,6,'Alkaline','root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Alkaline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (208,412,413,6,'Neutral','root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Neutral');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (209,414,415,6,'Sediment','root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (210,417,418,5,'Hot(42-90C)','root:Environmental:Aquatic:Thermal springs:Hot(42-90C)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (211,419,422,5,'Near-boiling (>90C)','root:Environmental:Aquatic:Thermal springs:Near-boiling (>90C)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (212,420,421,6,'Alkaline','root:Environmental:Aquatic:Thermal springs:Near-boiling (>90C):Alkaline');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (215,423,426,5,'Tepid (25-34C)','root:Environmental:Aquatic:Thermal springs:Tepid (25-34C)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (216,424,425,6,'Sediment','root:Environmental:Aquatic:Thermal springs:Tepid (25-34C):Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (217,427,432,5,'Warm (34-42C)','root:Environmental:Aquatic:Thermal springs:Warm (34-42C)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (218,428,429,6,'Neutral','root:Environmental:Aquatic:Thermal springs:Warm (34-42C):Neutral');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (219,430,431,6,'Sediment','root:Environmental:Aquatic:Thermal springs:Warm (34-42C):Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (213,434,437,4,'Thermal Springs','root:Environmental:Aquatic:Thermal Springs');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (214,435,436,5,'Sediment','root:Environmental:Aquatic:Thermal Springs:Sediment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (220,439,520,3,'Terrestrial','root:Environmental:Terrestrial');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (221,440,443,4,'Agricultural field','root:Environmental:Terrestrial:Agricultural field');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (222,441,442,5,'(null)','root:Environmental:Terrestrial:Agricultural field:(null)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (223,444,447,4,'Asphalt lakes','root:Environmental:Terrestrial:Asphalt lakes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (224,445,446,5,'Tar','root:Environmental:Terrestrial:Asphalt lakes:Tar');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (225,448,451,4,'Deep subsurface','root:Environmental:Terrestrial:Deep subsurface');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (226,449,450,5,'Clay','root:Environmental:Terrestrial:Deep subsurface:Clay');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (227,452,455,4,'Geologic','root:Environmental:Terrestrial:Geologic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (228,453,454,5,'Mine','root:Environmental:Terrestrial:Geologic:Mine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (229,456,457,4,'Oil reservoir','root:Environmental:Terrestrial:Oil reservoir');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (230,458,459,4,'Rock-dwelling (subaerial biofilms)','root:Environmental:Terrestrial:Rock-dwelling (subaerial biofilms)');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (231,460,515,4,'Soil','root:Environmental:Terrestrial:Soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (232,461,470,5,'Clay','root:Environmental:Terrestrial:Soil:Clay');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (233,462,463,6,'Agricultural land','root:Environmental:Terrestrial:Soil:Clay:Agricultural land');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (234,464,465,6,'Contaminated','root:Environmental:Terrestrial:Soil:Clay:Contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (235,466,467,6,'Grasslands','root:Environmental:Terrestrial:Soil:Clay:Grasslands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (236,468,469,6,'Oil-contaminated','root:Environmental:Terrestrial:Soil:Clay:Oil-contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (237,471,474,5,'Crop','root:Environmental:Terrestrial:Soil:Crop');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (238,472,473,6,'Agricultural land','root:Environmental:Terrestrial:Soil:Crop:Agricultural land');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (239,475,492,5,'Loam','root:Environmental:Terrestrial:Soil:Loam');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (240,476,477,6,'Agricultural','root:Environmental:Terrestrial:Soil:Loam:Agricultural');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (241,478,479,6,'Agricultural land','root:Environmental:Terrestrial:Soil:Loam:Agricultural land');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (242,480,481,6,'Agricultural soil','root:Environmental:Terrestrial:Soil:Loam:Agricultural soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (243,482,483,6,'Agricultural Soil','root:Environmental:Terrestrial:Soil:Loam:Agricultural Soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (244,484,485,6,'Contaminated','root:Environmental:Terrestrial:Soil:Loam:Contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (245,486,487,6,'Forest soil','root:Environmental:Terrestrial:Soil:Loam:Forest soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (246,488,489,6,'Forest Soil','root:Environmental:Terrestrial:Soil:Loam:Forest Soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (247,490,491,6,'Grasslands','root:Environmental:Terrestrial:Soil:Loam:Grasslands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (248,493,502,5,'Sand','root:Environmental:Terrestrial:Soil:Sand');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (249,494,495,6,'Desert','root:Environmental:Terrestrial:Soil:Sand:Desert');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (250,496,497,6,'Forest soil','root:Environmental:Terrestrial:Soil:Sand:Forest soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (251,498,499,6,'Grasslands','root:Environmental:Terrestrial:Soil:Sand:Grasslands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (252,500,501,6,'Oil-contaminated','root:Environmental:Terrestrial:Soil:Sand:Oil-contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (253,503,508,5,'Sand ','root:Environmental:Terrestrial:Soil:Sand ');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (254,504,505,6,'Desert','root:Environmental:Terrestrial:Soil:Sand :Desert');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (255,506,507,6,'Oil-contaminated','root:Environmental:Terrestrial:Soil:Sand :Oil-contaminated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (256,509,510,5,'Silt','root:Environmental:Terrestrial:Soil:Silt');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (257,511,514,5,'Wetlands','root:Environmental:Terrestrial:Soil:Wetlands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (258,512,513,6,'Permafrost','root:Environmental:Terrestrial:Soil:Wetlands:Permafrost');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (259,516,519,4,'Volcanic','root:Environmental:Terrestrial:Volcanic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (260,517,518,5,'Fumaroles','root:Environmental:Terrestrial:Volcanic:Fumaroles');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (261,522,963,2,'Host-associated','root:Host-associated');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (262,523,534,3,'Algae','root:Host-associated:Algae');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (263,524,525,4,'Brown Algae','root:Host-associated:Algae:Brown Algae');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (264,526,529,4,'Green algae','root:Host-associated:Algae:Green algae');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (265,527,528,5,'Ectosymbionts','root:Host-associated:Algae:Green algae:Ectosymbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (266,530,533,4,'Red algae','root:Host-associated:Algae:Red algae');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (267,531,532,5,'Ectosymbionts ','root:Host-associated:Algae:Red algae:Ectosymbionts ');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (268,535,540,3,'Amphibia','root:Host-associated:Amphibia');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (269,536,537,4,'Digestive system','root:Host-associated:Amphibia:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (270,538,539,4,'Excretory system','root:Host-associated:Amphibia:Excretory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (271,541,554,3,'Animal','root:Host-associated:Animal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (272,542,543,4,'Circulatory system','root:Host-associated:Animal:Circulatory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (273,544,547,4,'Digestive system','root:Host-associated:Animal:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (274,545,546,5,'Fecal','root:Host-associated:Animal:Digestive system:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (275,548,549,4,'Reproductive system','root:Host-associated:Animal:Reproductive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (276,550,551,4,'Respiratory system','root:Host-associated:Animal:Respiratory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (277,552,553,4,'Skin','root:Host-associated:Animal:Skin');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (278,555,582,3,'Annelida','root:Host-associated:Annelida');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (279,556,561,4,'Digestive system','root:Host-associated:Annelida:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (280,557,560,5,'Digestive tube','root:Host-associated:Annelida:Digestive system:Digestive tube');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (281,558,559,6,'Extracellular symbionts','root:Host-associated:Annelida:Digestive system:Digestive tube:Extracellular symbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (282,562,571,4,'Integument','root:Host-associated:Annelida:Integument');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (283,563,566,5,'Cuticle','root:Host-associated:Annelida:Integument:Cuticle');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (284,564,565,6,'Epibionts','root:Host-associated:Annelida:Integument:Cuticle:Epibionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (285,567,570,5,'Subcuticular space','root:Host-associated:Annelida:Integument:Subcuticular space');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (286,568,569,6,'Extracellular symbionts','root:Host-associated:Annelida:Integument:Subcuticular space:Extracellular symbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (287,572,575,4,'Intracellular endosymbionts','root:Host-associated:Annelida:Intracellular endosymbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (288,573,574,5,'Trophosome','root:Host-associated:Annelida:Intracellular endosymbionts:Trophosome');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (289,576,581,4,'Reproductive system','root:Host-associated:Annelida:Reproductive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (290,577,580,5,'Egg capsule','root:Host-associated:Annelida:Reproductive system:Egg capsule');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (291,578,579,6,'Extracellular','root:Host-associated:Annelida:Reproductive system:Egg capsule:Extracellular');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (292,583,628,3,'Arthropoda','root:Host-associated:Arthropoda');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (293,584,601,4,'Digestive system','root:Host-associated:Arthropoda:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (294,585,586,5,'Foregut','root:Host-associated:Arthropoda:Digestive system:Foregut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (295,587,592,5,'Gut','root:Host-associated:Arthropoda:Digestive system:Gut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (296,588,589,6,'P3 segment','root:Host-associated:Arthropoda:Digestive system:Gut:P3 segment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (297,590,591,6,'Proctodeal segment','root:Host-associated:Arthropoda:Digestive system:Gut:Proctodeal segment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (298,593,598,5,'Hindgut','root:Host-associated:Arthropoda:Digestive system:Hindgut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (299,594,595,6,'P1 segment','root:Host-associated:Arthropoda:Digestive system:Hindgut:P1 segment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (300,596,597,6,'P3 segment','root:Host-associated:Arthropoda:Digestive system:Hindgut:P3 segment');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (301,599,600,5,'Midgut','root:Host-associated:Arthropoda:Digestive system:Midgut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (302,602,607,4,'Integument','root:Host-associated:Arthropoda:Integument');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (303,603,606,5,'Cuticle','root:Host-associated:Arthropoda:Integument:Cuticle');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (304,604,605,6,'Thoracic segments','root:Host-associated:Arthropoda:Integument:Cuticle:Thoracic segments');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (305,608,615,4,'Intracellular endosymbionts','root:Host-associated:Arthropoda:Intracellular endosymbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (306,609,612,5,'Primary','root:Host-associated:Arthropoda:Intracellular endosymbionts:Primary');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (307,610,611,6,'Bacteriomes','root:Host-associated:Arthropoda:Intracellular endosymbionts:Primary:Bacteriomes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (308,613,614,5,'Secondary','root:Host-associated:Arthropoda:Intracellular endosymbionts:Secondary');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (309,616,619,4,'Respiratory system','root:Host-associated:Arthropoda:Respiratory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (310,617,618,5,'Gills','root:Host-associated:Arthropoda:Respiratory system:Gills');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (311,620,627,4,'Symbiotic fungal gardens and galleries','root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (312,621,622,5,'Fungus gallery','root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus gallery');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (313,623,626,5,'Fungus garden','root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus garden');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (314,624,625,6,'Garden dump','root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus garden:Garden dump');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (315,629,660,3,'Birds','root:Host-associated:Birds');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (316,630,633,4,'Circulatory system','root:Host-associated:Birds:Circulatory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (317,631,632,5,'Blood','root:Host-associated:Birds:Circulatory system:Blood');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (318,634,653,4,'Digestive system','root:Host-associated:Birds:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (319,635,638,5,'Ceca','root:Host-associated:Birds:Digestive system:Ceca');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (320,636,637,6,'Lumen','root:Host-associated:Birds:Digestive system:Ceca:Lumen');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (321,639,642,5,'Crop','root:Host-associated:Birds:Digestive system:Crop');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (322,640,641,6,'Lumen','root:Host-associated:Birds:Digestive system:Crop:Lumen');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (323,643,646,5,'Digestive tube','root:Host-associated:Birds:Digestive system:Digestive tube');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (324,644,645,6,'Cecum','root:Host-associated:Birds:Digestive system:Digestive tube:Cecum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (325,647,648,5,'Fecal','root:Host-associated:Birds:Digestive system:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (326,649,652,5,'Small intestine','root:Host-associated:Birds:Digestive system:Small intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (327,650,651,6,'Duodenal','root:Host-associated:Birds:Digestive system:Small intestine:Duodenal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (328,654,655,4,'Reproductive system','root:Host-associated:Birds:Reproductive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (329,656,659,4,'Respiratory system','root:Host-associated:Birds:Respiratory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (330,657,658,5,'Lungs','root:Host-associated:Birds:Respiratory system:Lungs');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (331,661,662,3,'Cnidaria','root:Host-associated:Cnidaria');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (332,663,664,3,'Echinodermata','root:Host-associated:Echinodermata');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (333,665,670,3,'Endosymbionts','root:Host-associated:Endosymbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (334,666,669,4,'Fungi','root:Host-associated:Endosymbionts:Fungi');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (335,667,668,5,'Endosymbionts','root:Host-associated:Endosymbionts:Fungi:Endosymbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (336,671,694,3,'Fish','root:Host-associated:Fish');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (337,672,675,4,'Circulatory system','root:Host-associated:Fish:Circulatory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (338,673,674,5,'Blood','root:Host-associated:Fish:Circulatory system:Blood');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (339,676,683,4,'Digestive system','root:Host-associated:Fish:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (340,677,680,5,'Foregut','root:Host-associated:Fish:Digestive system:Foregut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (341,678,679,6,'Uncharacterized','root:Host-associated:Fish:Digestive system:Foregut:Uncharacterized');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (342,681,682,5,'Intestine','root:Host-associated:Fish:Digestive system:Intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (343,684,687,4,'Excretory system','root:Host-associated:Fish:Excretory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (344,685,686,5,'Kidneys','root:Host-associated:Fish:Excretory system:Kidneys');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (345,688,689,4,'Reproductive system','root:Host-associated:Fish:Reproductive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (346,690,693,4,'Skin','root:Host-associated:Fish:Skin');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (347,691,692,5,'Slime','root:Host-associated:Fish:Skin:Slime');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (348,695,696,3,'Fungi','root:Host-associated:Fungi');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (349,697,800,3,'Human','root:Host-associated:Human');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (350,698,701,4,'Circulatory system','root:Host-associated:Human:Circulatory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (351,699,700,5,'Blood','root:Host-associated:Human:Circulatory system:Blood');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (352,702,739,4,'Digestive system','root:Host-associated:Human:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (353,703,706,5,'Hindgut','root:Host-associated:Human:Digestive system:Hindgut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (354,704,705,6,'Rectum','root:Host-associated:Human:Digestive system:Hindgut:Rectum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (355,707,708,5,'Intestine','root:Host-associated:Human:Digestive system:Intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (356,709,714,5,'Large intestine','root:Host-associated:Human:Digestive system:Large intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (357,710,711,6,'Fecal','root:Host-associated:Human:Digestive system:Large intestine:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (358,712,713,6,'Sigmoid colon','root:Host-associated:Human:Digestive system:Large intestine:Sigmoid colon');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (359,715,738,5,'Oral','root:Host-associated:Human:Digestive system:Oral');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (360,716,717,6,'Attached/Keratinized gingiva','root:Host-associated:Human:Digestive system:Oral:Attached/Keratinized gingiva');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (361,718,719,6,'buccal mucosa','root:Host-associated:Human:Digestive system:Oral:buccal mucosa');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (362,720,721,6,'Hard palate','root:Host-associated:Human:Digestive system:Oral:hard palate');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (363,722,723,6,'Palatine tonsils','root:Host-associated:Human:Digestive system:Oral:Palatine tonsils');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (364,724,725,6,'Periodontal pockets','root:Host-associated:Human:Digestive system:Oral:Periodontal pockets');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (365,726,727,6,'Saliva','root:Host-associated:Human:Digestive system:Oral:Saliva');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (366,728,729,6,'Subgingival plaque','root:Host-associated:Human:Digestive system:Oral:Subgingival plaque');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (367,730,731,6,'Subgingival plaque','root:Host-associated:Human:Digestive system:Oral:subgingival plaque');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (368,732,733,6,'Supragingival plaque','root:Host-associated:Human:Digestive system:Oral:Supragingival plaque');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (369,734,735,6,'Throat','root:Host-associated:Human:Digestive system:Oral:Throat');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (370,736,737,6,'Tongue dorsum','root:Host-associated:Human:Digestive system:Oral:tongue dorsum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (371,740,745,4,'Excretory system','root:Host-associated:Human:Excretory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (372,741,744,5,'Urethra','root:Host-associated:Human:Excretory system:Urethra');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (373,742,743,6,'Urine','root:Host-associated:Human:Excretory system:Urethra:Urine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (374,746,749,4,'Lympathic system','root:Host-associated:Human:Lympathic system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (375,747,748,5,'Lymph nodes','root:Host-associated:Human:Lympathic system:Lymph nodes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (376,750,751,4,'Milk','root:Host-associated:Human:Milk');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (377,752,755,4,'Nervous system','root:Host-associated:Human:Nervous system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (378,753,754,5,'Cerebrospinal fluid','root:Host-associated:Human:Nervous system:Cerebrospinal fluid');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (379,756,767,4,'Reproductive system','root:Host-associated:Human:Reproductive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (380,757,758,5,'Female','root:Host-associated:Human:Reproductive system:Female');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (381,759,766,5,'Vagina','root:Host-associated:Human:Reproductive system:Vagina');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (382,760,761,6,'Introitus','root:Host-associated:Human:Reproductive system:Vagina:Introitus');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (383,762,763,6,'Midpoint vagina','root:Host-associated:Human:Reproductive system:Vagina:Midpoint vagina');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (384,764,765,6,'Posterior fornix','root:Host-associated:Human:Reproductive system:Vagina:posterior fornix');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (385,768,783,4,'Respiratory system','root:Host-associated:Human:Respiratory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (386,769,774,5,'Nasopharyngeal','root:Host-associated:Human:Respiratory system:Nasopharyngeal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (387,770,771,6,'Anterior nares','root:Host-associated:Human:Respiratory system:Nasopharyngeal:anterior nares');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (388,772,773,6,'Pharynx','root:Host-associated:Human:Respiratory system:Nasopharyngeal:Pharynx');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (389,775,782,5,'Pulmonary system','root:Host-associated:Human:Respiratory system:Pulmonary system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (390,776,777,6,'Sputum','root:Host-associated:Human:Respiratory system:Pulmonary system:Sputum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (391,778,779,6,'Trachea','root:Host-associated:Human:Respiratory system:Pulmonary system:Trachea');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (392,780,781,6,'Viriome','root:Host-associated:Human:Respiratory system:Pulmonary system:Viriome');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (393,784,799,4,'Skin','root:Host-associated:Human:Skin');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (394,785,786,5,'Axilla','root:Host-associated:Human:Skin:Axilla');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (395,787,790,5,'Medial distal leg','root:Host-associated:Human:Skin:Medial distal leg');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (396,788,789,6,'Venous leg ulcers','root:Host-associated:Human:Skin:Medial distal leg:Venous leg ulcers');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (397,791,792,5,'Naris','root:Host-associated:Human:Skin:Naris');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (398,793,794,5,'retroauricular crease','root:Host-associated:Human:Skin:retroauricular crease');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (399,795,796,5,'Umbilicus','root:Host-associated:Human:Skin:Umbilicus');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (400,797,798,5,'Volar forearm','root:Host-associated:Human:Skin:Volar forearm');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (401,801,804,3,'Insecta','root:Host-associated:Insecta');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (402,802,803,4,'Digestive system','root:Host-associated:Insecta:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (403,805,818,3,'Invertebrates','root:Host-associated:Invertebrates');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (404,806,809,4,'Bryozoans','root:Host-associated:Invertebrates:Bryozoans');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (405,807,808,5,'Gymnolaemates','root:Host-associated:Invertebrates:Bryozoans:Gymnolaemates');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (406,810,813,4,'Cnidaria','root:Host-associated:Invertebrates:Cnidaria');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (407,811,812,5,'Coral','root:Host-associated:Invertebrates:Cnidaria:Coral');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (408,814,817,4,'Echinodermata','root:Host-associated:Invertebrates:Echinodermata');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (409,815,816,5,'Sea Urchin','root:Host-associated:Invertebrates:Echinodermata:Sea Urchin');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (410,819,830,3,'Mammal','root:Host-associated:Mammal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (411,820,829,4,'Digestive system','root:Host-associated:Mammal:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (412,821,824,5,'Large Intestine','root:Host-associated:Mammal:Digestive system:Large Intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (413,822,823,6,'Fecal','root:Host-associated:Mammal:Digestive system:Large Intestine:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (414,825,828,5,'Stomach','root:Host-associated:Mammal:Digestive system:Stomach');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (415,826,827,6,'Rumen','root:Host-associated:Mammal:Digestive system:Stomach:Rumen');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (416,831,896,3,'Mammals','root:Host-associated:Mammals');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (417,832,835,4,'Circulatory system','root:Host-associated:Mammals:Circulatory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (418,833,834,5,'Blood','root:Host-associated:Mammals:Circulatory system:Blood');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (419,836,863,4,'Digestive system','root:Host-associated:Mammals:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (420,837,840,5,'Fecal','root:Host-associated:Mammals:Digestive system:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (421,838,839,6,'Uncharacterized','root:Host-associated:Mammals:Digestive system:Fecal:Uncharacterized');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (422,841,844,5,'Foregut','root:Host-associated:Mammals:Digestive system:Foregut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (423,842,843,6,'Rumen','root:Host-associated:Mammals:Digestive system:Foregut:Rumen');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (424,845,850,5,'Large intestine','root:Host-associated:Mammals:Digestive system:Large intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (425,846,847,6,'Cecum','root:Host-associated:Mammals:Digestive system:Large intestine:Cecum');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (426,848,849,6,'Fecal','root:Host-associated:Mammals:Digestive system:Large intestine:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (427,851,852,5,'Midgut','root:Host-associated:Mammals:Digestive system:Midgut');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (428,853,856,5,'Oral cavity','root:Host-associated:Mammals:Digestive system:Oral cavity');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (429,854,855,6,'Buccal mucosa','root:Host-associated:Mammals:Digestive system:Oral cavity:Buccal mucosa');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (430,857,862,5,'Stomach','root:Host-associated:Mammals:Digestive system:Stomach');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (431,858,859,6,'Endoperitrophic space','root:Host-associated:Mammals:Digestive system:Stomach:Endoperitrophic space');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (432,860,861,6,'Rumen','root:Host-associated:Mammals:Digestive system:Stomach:Rumen');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (433,864,865,4,'Excretory system','root:Host-associated:Mammals:Excretory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (434,866,871,4,'Gastrointestinal tract','root:Host-associated:Mammals:Gastrointestinal tract');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (435,867,870,5,'Intestine','root:Host-associated:Mammals:Gastrointestinal tract:Intestine');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (436,868,869,6,'Fecal','root:Host-associated:Mammals:Gastrointestinal tract:Intestine:Fecal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (437,872,875,4,'Lymphatic','root:Host-associated:Mammals:Lymphatic');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (438,873,874,5,'Lymph nodes','root:Host-associated:Mammals:Lymphatic:Lymph nodes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (439,876,877,4,'Milk','root:Host-associated:Mammals:Milk');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (440,878,881,4,'Nervous system','root:Host-associated:Mammals:Nervous system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (441,879,880,5,'Brain','root:Host-associated:Mammals:Nervous system:Brain');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (442,882,883,4,'Reproductive system','root:Host-associated:Mammals:Reproductive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (443,884,893,4,'Respiratory system','root:Host-associated:Mammals:Respiratory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (444,885,888,5,'Nasopharyngeal','root:Host-associated:Mammals:Respiratory system:Nasopharyngeal');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (445,886,887,6,'Nasal cavity','root:Host-associated:Mammals:Respiratory system:Nasopharyngeal:Nasal cavity');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (446,889,892,5,'Pulmonary system','root:Host-associated:Mammals:Respiratory system:Pulmonary system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (447,890,891,6,'Viriome','root:Host-associated:Mammals:Respiratory system:Pulmonary system:Viriome');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (448,894,895,4,'Skin','root:Host-associated:Mammals:Skin');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (449,897,904,3,'Microbial','root:Host-associated:Microbial');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (450,898,899,4,'Bacteria','root:Host-associated:Microbial:Bacteria');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (451,900,903,4,'Dinoflagellates','root:Host-associated:Microbial:Dinoflagellates');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (452,901,902,5,'Endosymbionts','root:Host-associated:Microbial:Dinoflagellates:Endosymbionts');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (453,905,924,3,'Mollusca','root:Host-associated:Mollusca');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (454,906,913,4,'Digestive system','root:Host-associated:Mollusca:Digestive system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (455,907,910,5,'Ceca','root:Host-associated:Mollusca:Digestive system:Ceca');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (456,908,909,6,'Uncharacterized','root:Host-associated:Mollusca:Digestive system:Ceca:Uncharacterized');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (457,911,912,5,'Glands','root:Host-associated:Mollusca:Digestive system:Glands');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (458,914,921,4,'Respiratory system','root:Host-associated:Mollusca:Respiratory system');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (459,915,920,5,'Gills','root:Host-associated:Mollusca:Respiratory system:Gills');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (460,916,917,6,'Extracellular','root:Host-associated:Mollusca:Respiratory system:Gills:Extracellular');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (461,918,919,6,'Intracellular','root:Host-associated:Mollusca:Respiratory system:Gills:Intracellular');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (462,922,923,4,'Shell','root:Host-associated:Mollusca:Shell');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (463,925,950,3,'Plants','root:Host-associated:Plants');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (464,926,931,4,'Phylloplane','root:Host-associated:Plants:Phylloplane');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (465,927,928,5,'Endophytes','root:Host-associated:Plants:Phylloplane:Endophytes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (466,929,930,5,'Epiphytes','root:Host-associated:Plants:Phylloplane:Epiphytes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (467,932,935,4,'Rhizome','root:Host-associated:Plants:Rhizome');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (468,933,934,5,'Epiphytes','root:Host-associated:Plants:Rhizome:Epiphytes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (469,936,943,4,'Rhizoplane','root:Host-associated:Plants:Rhizoplane');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (470,937,938,5,'Endophytes','root:Host-associated:Plants:Rhizoplane:Endophytes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (471,939,940,5,'Epiphytes','root:Host-associated:Plants:Rhizoplane:Epiphytes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (472,941,942,5,'Soil','root:Host-associated:Plants:Rhizoplane:Soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (473,944,949,4,'Rhizosphere','root:Host-associated:Plants:Rhizosphere');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (474,945,946,5,'Epiphytes','root:Host-associated:Plants:Rhizosphere:Epiphytes');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (475,947,948,5,'Soil','root:Host-associated:Plants:Rhizosphere:Soil');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (476,951,952,3,'Porifera','root:Host-associated:Porifera');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (477,953,954,3,'Protists','root:Host-associated:Protists');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (478,955,956,3,'Protozoa','root:Host-associated:Protozoa');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (479,957,958,3,'Reptilia','root:Host-associated:Reptilia');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (480,959,962,3,'Tunicates','root:Host-associated:Tunicates');
INSERT INTO biome_hierarchy_tree (biome_id,lft,rgt,depth,biome_name,lineage) values (481,960,961,4,'Ascidians','root:Host-associated:Tunicates:Ascidians');