insert into EMG_USER.HB_STUDY (CENTRE_NAME, EXPERIMENTAL_FACTOR, IS_PUBLIC, NCBI_PROJECT_ID, PUBLIC_RELEASE_DATE, STUDY_ABSTRACT, STUDY_ID, STUDY_NAME, STUDY_STATUS, STUDY_TYPE, SUBMITTER_ID)
values ("test", "", 1, 1, null, "", 212, "rain forest soil", 0, 0, 512);

insert into EMG_USER.HB_STUDY (CENTRE_NAME, EXPERIMENTAL_FACTOR, IS_PUBLIC, NCBI_PROJECT_ID, PUBLIC_RELEASE_DATE, STUDY_ABSTRACT, STUDY_ID, STUDY_NAME, STUDY_STATUS, STUDY_TYPE, SUBMITTER_ID)
values ("test", "", 1, 1, null, "", 212, "atlantic ocean", 1, 1, 512);

insert into EMG_USER.HB_STUDY (CENTRE_NAME, EXPERIMENTAL_FACTOR, IS_PUBLIC, NCBI_PROJECT_ID, PUBLIC_RELEASE_DATE, STUDY_ABSTRACT, STUDY_ID, STUDY_NAME, STUDY_STATUS, STUDY_TYPE, SUBMITTER_ID)
values ("test", "", 0, 1, null, "", 212, "ostsee", 2, 2, 512);
